// pkg/go/parser/parseexprfrom.
package main

// TODO: fix

import (
	"go/ast"
	"go/format"
	"go/token"
	"os"
)

func main() {
	ident := ast.NewIdent("AutoGenerated")
	ident.Obj = ast.NewObj(ast.Typ, "struct")
	ident.Obj.Decl = ast.Field{
		Names: []*ast.Ident{
			ast.NewIdent("hello"),
		},
	}

	err := format.Node(os.Stdout, token.NewFileSet(), ident)
	if err != nil {
		panic(err)
	}
}
